// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgzTBxaUBaEqhqKsxvXWqq5iBqEFq_pc',
    appId: '1:514819484900:android:6ff2ee4e48c2d622b010f1',
    messagingSenderId: '514819484900',
    projectId: 'instaclone-37642',
    storageBucket: 'instaclone-37642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyeVayNoiGB3eQcJjCTOFNrDtiS0G3bNI',
    appId: '1:514819484900:ios:70d6e248655baa46b010f1',
    messagingSenderId: '514819484900',
    projectId: 'instaclone-37642',
    storageBucket: 'instaclone-37642.appspot.com',
    iosClientId: '514819484900-hg8q7tsvpdrpa16k8phl01h16bkovuh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
